// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Título do Hero field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Descrição do Hero field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_description: prismic.RichTextField;

  /**
   * Imagem de Capa field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>
  /**
   * Título field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.about_title
   * - **Tab**: Sobre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  about_title: prismic.KeyTextField;

  /**
   * Descrição field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.about_description
   * - **Tab**: Sobre
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_description: prismic.RichTextField;

  /**
   * Imagem Carrossel 01 field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.carousel_img_01
   * - **Tab**: Sobre
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carousel_img_01: prismic.ImageField<never>;

  /**
   * Imagem Carrossel 02 field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.carousel_img_02
   * - **Tab**: Sobre
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carousel_img_02: prismic.ImageField<never>;

  /**
   * Imagem Carrossel 03 field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.carousel_img_03
   * - **Tab**: Sobre
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carousel_img_03: prismic.ImageField<never>
  /**
   * Título field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.categories_title
   * - **Tab**: Categorias
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  categories_title: prismic.KeyTextField;

  /**
   * Descrição field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.categories_description
   * - **Tab**: Categorias
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  categories_description: prismic.RichTextField
  /**
   * Título field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.opportunities_title
   * - **Tab**: Oportunidades
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  opportunities_title: prismic.KeyTextField;

  /**
   * Descrição field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.opportunities_description
   * - **Tab**: Oportunidades
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  opportunities_description: prismic.RichTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Content for Oportunity documents
 */
interface OportunityDocumentData {
  /**
   * Título field in *Oportunity*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Categoria field in *Oportunity*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Trabalho no exterior"
    | "Trabalho remoto"
    | "Trabalho voluntário"
    | "Bolsas de estudos"
    | "Intercâmbios"
    | "Cursos internacionais"
  >;

  /**
   * Destino field in *Oportunity*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.destination
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;

  /**
   * Descrição field in *Oportunity*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link  field in *Oportunity*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Capa field in *Oportunity*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: oportunity.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;
}

/**
 * Oportunity document from Prismic
 *
 * - **API ID**: `oportunity`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OportunityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OportunityDocumentData>,
    "oportunity",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument | OportunityDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      OportunityDocument,
      OportunityDocumentData,
      AllDocumentTypes,
    };
  }
}
